package com.companyfiller.android.brieflyboxing

import android.os.Bundle
import android.support.v7.app.AppCompatActivity
import android.support.v7.widget.RecyclerView
import android.util.Log

/**
 * Created by Chase on 2/21/2018.
 */
class ShowMovesActivity: AppCompatActivity() {

    private val recyclerView: RecyclerView by lazy { findViewById<RecyclerView>(R.id.moves_recycler) }

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_show_moves)
    }

    override fun onStart() {
        super.onStart()
        Log.i("Asshat", "Here are the moves generated by the random thing: " + MoveGenerator.getRandomMoves(5))
        //TODO put the random moves into the recycler view
        //TODO make it so that the number of moves will react to the user's input
    }

}